### ISSUE TITLE
I am no longer able to use any of the commands

### ISSUE THREAD

**Issue by RyanMcArthur** [karikera/vscode-closure-compiler#3]
I was using the extension without issue yesterday. I went to use the command "Closure Compiler: Compile All" and it results in this error. It appears to do this for all commands.

![image](https://user-images.githubusercontent.com/47610962/82103765-f0c91100-96d9-11ea-94b9-fc8068e3067d.png)

Let me know if there's any other info you need from me.

**Comment by RyanMcArthur** [comment]
I reverted to the previous version and things work fine. If you need anything from me to reproduce and give logs of sorts I can update it and try again, I'll just need to know what you need.

**Comment by karikera** [comment]
Thank for reporting! I will fix it

**Comment by karikera** [comment]
It's now fixed! (1.3.3)
